### ISSUE TITLE
Xfailed tests

### ISSUE THREAD

**Issue by cartemic** [corykinney/RGFROSH#16]
I noticed that there are some tests marked with xfail, but I don't see any documentation about why these cases are expected to fail. Is this something that should be addressed before release?

**Comment by corykinney** [comment]
@cartemic The tests marked with xfail have been resolved. It was suspected that there were a couple of errors in the book that the ideal shock equations and validation data was pulled from, but it was never investigated and removed. Issues #5 and #11 were the corresponding issues that have now been addressed.
